export type AppPhase =
  | "build"
  | "generate"
  | "study"
  | "recall"
  | "results"
  | "mistakes";

export type GenerationKind = "idle" | "route" | "image";

export const PHASE_TITLE: Record<AppPhase, string> = {
  build: "Build",
  generate: "Generate",
  study: "Study",
  recall: "Recall",
  results: "Results",
  mistakes: "Mistakes",
};

export const PHASE_SUBTITLE: Record<AppPhase, string> = {
  build: "Choose your sequence",
  generate: "Building your route",
  study: "Walk the route in order",
  recall: "Name the item at each stop",
  results: "Your run",
  mistakes: "Stops you missed",
};

export function phaseTitle(phase: AppPhase) {
  return PHASE_TITLE[phase];
}

export function phaseSubtitle(phase: AppPhase) {
  return PHASE_SUBTITLE[phase];
}

export const APP_KICKER = "Memory palace · AI-built route";

export const APP_DESCRIPTION =
  "A language model designs each stop and renders a scene image so you can walk a vivid sequence in your head.";

export const AI_DISCLOSURE_LINE =
  "Route text and images are generated by AI and may be imperfect — use them as creative anchors, not facts.";

export function phaseAiHint(phase: AppPhase): string {
  switch (phase) {
    case "build":
      return "You choose the ordered list; the model invents locations, cues, and imagery.";
    case "generate":
      return "Each stop is written, then illustrated — this can take a short while.";
    case "study":
      return "Treat scenes as mnemonic anchors linking your items to the path.";
    case "recall":
      return "Only your memory and the scene image — name each item in order.";
    case "results":
      return "Review how the sequence held; scenes are the same ones you studied.";
    case "mistakes":
      return "These are the stops that did not match. You can rebuild from just the missed keywords.";
  }
}

export const BUILD_AI_FOOTNOTE =
  "AI will invent locations, cues, and scene images from your list. You only need the exact items in order.";

function pad2(value: number) {
  return String(value).padStart(2, "0");
}

export function formatStopLabel(step: number, total: number) {
  return `Stop ${pad2(step)} of ${pad2(total)}`;
}

export function formatStopShort(step: number, total: number) {
  return `${pad2(step)} / ${pad2(total)}`;
}

export function generationLine(
  kind: Exclude<GenerationKind, "idle">,
  step: number,
  total: number,
) {
  if (kind === "route") {
    return `Generating stop ${step} of ${total}`;
  }

  return `Rendering image ${step} of ${total}`;
}

export const CTA = {
  buildPalace: "Build palace",
  nextStop: "Next stop",
  previousStop: "Previous stop",
  startRecall: "Start recall",
  submit: "Submit",
  reviewMisses: "Review misses",
  buildFromMisses: "Build new palace from misses",
  restart: "Restart",
  retryStop: "Retry stop",
  retryImage: "Retry image",
  skipImage: "Skip image",
  cancelRun: "Cancel run",
  done: "Done",
} as const;

export const ERROR_TITLE = {
  route: (step: number) => `Stop ${pad2(step)} failed`,
  image: (step: number) => `Image ${pad2(step)} failed`,
} as const;
